build/jsdoc/api/conf.json
build/jsdoc/api/plugins/typedefs.js
externs/olcsx.js
src/ol3cesium.js

This change allows developers to configure a `createSymbolizers` function for OLCesium, instead of relying on the default set of synchronizers.

Allow working with custom synchronizers

---

Cesium.externs.js
src/core.js

Handle opacity property in the converter.

Set billboard opacity

---

CHANGES.md
Makefile

Update of the CHANGE.md, the OL3 and Cesium dependencies.
Trivial fix for the generation of the exemple-list.js.

Release 2015 01 20

---

examples/vectors.js
src/core.js

Closes #161
Updated vectors example to include a feature without geometry.

Handle features without geometry

---

Makefile

The example-list.js file was generated after the copy of the
example repository to dist directory.

Generate example-list.js earlier

---

Cesium.externs.js
src/core.js

Deprecated `setTransform` will be removed in next release of Cesium.

Stop using deprecated setTransform

---

Cesium.externs.js
src/core.js

This PR adds a core function for computing a bounding box at a target point.
It takes into account the terrain and may be used for creating a WFS query...

Core function for computing bounding box

---

src/ol3cesium.js

Disabling a disabled ol3cs is an error and is now avoided.
Make the API more regular by requiring a parameter.

Fix ol3cs.setEnabled

---

src/core.js

This attribute does not exist in Cesium.

Remove unused width attribute in polygon outline

---

src/core/olimageryprovider.js

This PR allows custom build when removing the "ignoreRequires" option.

Remove useless goog.require

---

src/vectorsynchronizer.js

When doing feature.setGeometry(null) on a Point feature, the Cesium
counterpart (Billboard) was not removed properly.
This PR handles this case.
The case when there is no geometry and no associated billboard is found
for this feature id is also handled.

Fix removal of billboard in the absence of a geometry

---

src/core.js

To be able to control the animation of `olcs.core.setHeadingUsingBottomCenter`

Add new RotateAroundAxisOption param to setHeadingUsingBottomCenter

---

CHANGES.md
src/plugins/.gitignore
src/plugins/README.md

Allow compiling application code with the OL3-Cesium library by simply
putting plugin javascript code in the src/plugins directory.
User automatically gets error checking, styling and documentation.
This extension mechanism is intended for people not familiar with
Closure. More advanced use-cases should be handled with a custom build.

Simple plugin mechanism

---

CHANGES.md
build/generate-info.js

Fixes symlink plugins exports missing from dist/exports.js.

Follow symlinks in build/generate-info.js

---

CHANGES.md
src/ol3cesium.js

This PR allows blocking Cesium rendering which is useful to save
resources. When no interaction is expected on the map, the application
can choose to block Cesium loop. Later on it may be unblocked.

Simple cesium resource control

---

Cesium.externs.js
examples/rastersync.html
examples/rastersync.js
src/abstractsynchronizer.js
src/core/vectorlayercounterpart.js
src/featureconverter.js
src/rastersynchronizer.js
src/vectorsynchronizer.js

This PR reworks the synchronizers to fix several issues, notably the blue flash when adding/updating and removing layers, and implements Z-index ordering of raster layers.
The abstract synchronizer used to remove all layers from Cesium before any operation (add, update and remove). Now layers are removed only when needed, which prevents the blue flash.
Additionnally, the following issues were fixed:
- buggy transposition of `this.layerMap`;
- missing clean up of vector synchronizer listeners.

Seamless layer synchronization + z-index

---

src/abstractsynchronizer.js
src/core/olimageryprovider.js
src/featureconverter.js
src/ol3cesium.js

Prefer standard Ecmascript 5.1 array.forEach instead of the function
provided by the closure library. This is part of a work to shrink dependency
on goog library.

Remove goog.array.forEach

---

Cesium.externs.js
examples/vectors.html
examples/vectors.js
src/featureconverter.js

Use GroundPrimitive instead of Primitive when altittudeMode is set to clampToGround.
Ready for review @gberaudo .

GroundPrimitive

---

Makefile

For example, compile Cesium in release mode with:
"make cesium/Build/Cesium/Cesium.js -e CESIUM_COMPILE_TARGET=release".

Allow specifying Cesium compilation target

---

src/ol3cesium.js

When initialising ol3-cesium in 2D mode, the size of the canvas used is not correct. This will result in the wrong distance being calculated for the cesium camera.
The distance is calculated in the [`readView`](https://github.com/openlayers/ol3-cesium/blob/b06886cdb0958a75ff209782ac1af05bfebd6beb/src/camera.js#L378) function of the olcs.camera which is using the canvas dimensions.

Calculate Canvas size on initialisation

---

Cesium.externs.js
src/ol3cesium.js

Trivial patch from @poppycocker.
Closes #262

Fix typo 'ineartia' to 'inertia'.

---

src/abstractsynchronizer.js

Without removing the layerGroup from the `layerMap` list, we can't re-add it.

Remove the group from layerMap list when it is removed

---

src/abstractsynchronizer.js
src/rastersynchronizer.js

See #266 from @oterral.
This version simplifies layers traversal by getting ride of `olcs.AbstractSynchronizer.flattenLayer`.

Handle Z-Index for groups

---

Cesium.externs.js
examples/kml.html
examples/kml.js
src/ol3cesium.js

This PR adds the possibility to add datasources (KML, GEOJson) to the Cesium rendered view.
The handling of the datasources themselves are the responsibility of the clients of ol3-cesium.

Add possibility to add datasources to 3D view

---

CHANGES.md
Cesium.externs.js
examples/vectors.js
src/autorenderloop.js
src/ol3cesium.js

This PR is an adaptation of [some code from Kevin Ring (NICTA)](https://github.com/TerriaJS/terriajs/blob/ebd382a8278a817fce316730d9e459bbb9b829e9/lib/Models/Cesium.js).
It allows automatically rendering the Cesium globe only when necessary, saving a lot of resource and battery on mobile devices.
The source project uses the Apache v2 license so I kept the code in a single file: `src/autorenderloop.js
` and added a comment at the top of the file. Is it OK to handle Apache2 code this way?
@kring, does it look fine for you?
This is `experimental` and `opt-in`: see the vector example for an example of use.
In the long run, it would be nice to have this directly in Cesium; there is a reflexion about it here:
https://github.com/AnalyticalGraphicsInc/cesium/issues/1865.

Auto stop render loop

---

src/camera.js

Due to inertia and computation instabilities, synchronization may be very long.
This change allows faster synchronization.

Add epsilon to camera change check

---

externs/olcsx.js

Moving the undefined at the start fixed the error.
Closes #157.

Fix API doc generation

---

Cesium.externs.js
Makefile
src/camera.js

Cesium switched its build system from ant to gulp.
This version also renamed/deprecated some APIs.
Todo later: use RectangleGeometry instead of RectanglePrimitive for selection.
See #277.
Update: add link to 277 issue

Port to Cesium master (gulp, deprecated/removed API)

---

Cesium.externs.js
src/ol3cesium.js

Using `time` the sky was not rendered anymore.

Fix sky rendering

---

CHANGES.md
src/camera.js
src/core.js
src/ol3cesium.js

Add `olcs.OLCesium.setResolutionScale` to allow improving performance at the cost of quality.
Automatically use device pixel ratio to configure the Webgl 3D globe.

Honour pixel ratio and allow degrading quality for performance

---

src/abstractsynchronizer.js

When a layer group is removed, first try to remove the group
counterparts. If unsucessful, try to remove each of the group children.

Fix group removal

---

CHANGES.md
CONTRIBUTING.md
Makefile
build/build.js
build/generate-info.js
build/ol3cesium-debug.json
build/ol3cesium.json
build/serve.js
closure-util.json
examples/dragbox.html
examples/epsg-4326.html
examples/exports.html
examples/kml.html
examples/lazy.html
examples/main.html
examples/rastersync.html
examples/selection.html
examples/sidebyside.html
examples/synthvectors.html
examples/synthvectors_batch.html
examples/vectors.html
package.json
src/featureconverter.js
src/olcs.js

OL3-Cesium used to be compiled against OL3 externs.
This was unnatural for a Closure project and had shortcomings:
- a custom closure compiler was required;
- we were restricted to OL3 @api symbols;
- OL3 externs were sometimes buggy;
- the goog library was included twice;
...
This change bundles the OL3 code together with OL3-Cesium, which is already what we do in Ngeo.
This will allow adding client side raster reprojection in the future.

Compile OL3-Cesium together with OL3

---

CHANGES.md
src/ol3cesium.js

The Cesium team updated their default handling of pixel ratio.
On devices with pixelRatio > 1, the buffer used for rendering the scene will be smaller than the size of the canvas (clientWidth, clientHeight) and scaled afterwards.
This change drastically improves FPS on smartphones and reduces bandwidth usage.

Honor devicePixelRatio like in Cesium

---

CHANGES.md
src/ol3cesium.js

Reverts openlayers/ol3-cesium#290
The Cesium team is thinking about reverting their change:
https://github.com/AnalyticalGraphicsInc/cesium/issues/3249.

Revert "Honor devicePixelRatio like in Cesium"

---

Cesium.externs.js
src/ol3cesium.js

Allow adding Cesium entities to the globe.
See https://groups.google.com/forum/#!topic/ol3-dev/koro6VTogn0
```
var entity = {
name: 'Green wall from surface with outline',
wall: {
positions: Cesium.Cartesian3.fromDegreesArrayHeights(
[-107.0, 43.0, 100000.0, -107.0, 40.0, 100000.0, -107.0, 43.0, 100000.0]
),
material: Cesium.Color.GREEN
}
}
ol3d.getDataSourceDisplay().defaultDataSource.entities.add(entity);
```

Add entities to the globe

---

Cesium.externs.js
src/featureconverter.js

Take into account scale on icons

---

src/abstractsynchronizer.js

Layers in a layergroup were not properly removed.
Remove counterparts associated to individual layers when there is no
counterpart associated to the group itself.

Fix layer group removal

---

Cesium.externs.js
externs/olcsx.js
src/ol3cesium.js

I added some code for passing `Cesium.Scene` initialization parameters to the `olcs.OLCesium` object. In my use case this allowed me to pass a *terrainExaggeration* value. `Cesium.Scene` offers a range of interesting settings, which is why I think it should be possible to pass parameters to it.

Allow passing of Cesium.Scene initialization properties

---

src/rastersynchronizer.js

Layer group sublayers were appended to the queue instead of being
prepended. As a consequence, a single layer positioned after a group
was ordered first.
This commit prepends the sublayers so that they are handled first.

Fix layer ordering

---

CHANGES.md
Cesium.externs.js
examples/vectors.js
src/featureconverter.js

This PR is to support Cesium rectangles.
Closes: https://github.com/openlayers/ol3-cesium/issues/355.
We should document this functionality somewhere, as it is not straightforward.
`geometry.set('olcs.polygon_kind', 'rectangle');`

Add support for Cesium rectangles

---

CHANGES.md
src/core/olimageryprovider.js

Add support to set a proxy for Cesium to load layer not accessible due to missing CORS headers (eg. when user can't modify configuration of the mapservice used). This functionality can be activated by setting the olcs.proxy property to the OpenLayers source.
The following error occurs if CORS is not configured on the remote service:
```
Image from origin 'http://remote.service.org' has been blocked from loading 
by Cross-Origin Resource Sharing policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
The ```olcs.proxy``` property can contains:
* a function
```
source.set('olcs.proxy', function (url) {
return '/myproxy?url=' + encodeURIComponent(url);
});
```
* a string pointing to the proxy. In that case a ```Cesium.DefaultProxy``` will be configured on …

Configure proxy to use to retrieve tiles.

---

examples/vectors.js
src/featureconverter.js

All browsers on Windows only support a maximum WebGL width of 1.
This commit adds support for arbitrary width.

Support arbitrary line widths on windows

---

src/ol3cesium.js

All the examples continue to work as expected

Remove the Cesium camera inertia limitation

---

build/jsdoc/api/readme.md
src/core/olimageryprovider.js

The build file (`dist/ol3cesium.js`) is the same as before.

Use export tag instead of goog.exportProperty

---

examples/vectors.html
examples/vectors.js
src/ol3cesium.js

I added a function to set the target rendering frame rate for Cesium. Our application is using this to reduce the frame rate while parsing large data sets, which speeds up parsing significantly while still providing occasional feedback to the user that data is loading.
@ahocevar or @gberaudo could you review please? Thanks!

Allow setting target rendering frame rate

---

src/autorenderloop.js

Updated the tile checks in `olcs.AutoRenderLoop#postRender` to match those used in `Cesium.Camera#update`. Considered using the `_suspendTerrainAdjustment` private flag in the Cesium camera, but that seemed more fragile to change and less clear to someone trying to understand the olcs code.

Update Cesium private variables in render loop

---

CHANGES.md
Cesium.externs.js
src/featureconverter.js

It corresponds to the hack in Cesium.KmlDataSource.

Use GroundPrimitive for line

---

build/generate-info.js

This PR updates `build/generate-info.js` to allow Windows user to build ol-cesium. I used [openlayers/tasks/generate-info.js](https://github.com/openlayers/openlayers/blob/46c610f35e0adb89f73bb49c3d472d126e28b63c/tasks/generate-info.js) as a reference

Building on Windows

---

src/featureconverter.js

`olFeatureToCesium` can return null value, when it is the case `prims.get` returns a js error.

Manage null value of prims variable

---

.gitmodules
.travis.yml
CHANGES.md
Makefile
build/build.js
build/generate-info.js
build/olcesium-debug.json
build/olcesium.json
build/serve.js
examples/exports.html
examples/inject_ol_cesium.js
examples/kml.html
examples/lazy.html
examples/main.html
examples/rastersync.html
examples/rotate.html
examples/selection.html
examples/sidebyside.html
examples/synthvectors_batch.html
examples/tracking.html
examples/vectors.html
package.json

Switch to @camptocamp/closure-util to allow usage of goog.modules.
Applications using closure will need to switch to @camptocamp/closure-util.
In the middle term the dependency on closure-util will be removed in favour of pure ES6 modules.
Switch to @camptocamp/cesium to allow writing examples using Cesium vector tiles or advanced optimizations.

Depend on OpenLayers and Cesium through npm

---

src/olcs/featureconverter.js

just fixes a small bug i saw when i did some of the other work. 
computeplainstyle can return null, so we have to check for null
Jannes

add nullcheck, computeplainstyle can return null

---

CHANGES.md
src/olcs/featureconverter.js
src/olcs/vectorsynchronizer.js

next PR for the city of hamburg project see #494
this fixes https://github.com/openlayers/ol-cesium/issues/493
we changed the handling of cluster sources. As a first iteration we use the real features to convert to cesium. 
As a second iteration someone could intergrate the cesium clustering support.
Jannes

Do not use cluster source, but the underlying feature source

---

CHANGES.md
src/olcs/camera.js

in the Hamburg project, we would like to use the olcs.camera.calcResolutionForDistance function so we don't have to implement the same functionality. 
This PR just exports calcResoltionForDistance and calcDistanceForResolution so functions can be used from a thirdparty library

extend Camera API

---

CHANGES.md
examples/layer-group.html
examples/layer-group.js
externs/olcsx.js
src/olcs/abstractsynchronizer.js
src/olcs/core.js
src/olcs/rastersynchronizer.js
src/olcs/vectorsynchronizer.js

Hi, 
we are at the moment working on a project to integrate 3D in the 2D gis portal of Hamburg. For this we are using ol-cesium, but we had to add some functionality and now want to integrate the changes in the project. 
For better review purposes i will create several pull requests. 
Here we changed the code to also synchronize nested ol.layer.group Items. 
Link to the hamburg application: https://www.geoportal-hamburg.de/Geoportal/geo-online/
Link to the Hamburg application source code: https://bitbucket.org/lgv-g12/lgv
This work is paid by the Agency for Geoinformation and Surveying (LGV) Hamburg
http://www.hamburg.de/bsw/whoweare/
Jannes

synchronize nested ol.layer.group Items

---

package.json

Hello,
In order to import ol-cesium in our Angular application, it needs to register a "main" entry in the package.json.
Thanks

Add main entry in package.json

---

CHANGES.md
externs/olcsx.js
src/olcs/olcesium.js

The goal of OL-Cesium is to unify interacting with OpenLayers and Cesium.
Letting the events be propagated to OpenLayers allows to have a single listener in application code, designed around the OpenLayers API.

Stop OpenLayers events propagation with a flag

---

CHANGES.md
package.json
src/olcs/featureconverter.js
src/olcs/vectorsynchronizer.js

This PR prepare for v4.6.0 of openlayer removing use of ol.source.ImageVector.

Remove management of ol.source.ImageVector

---

.eslintrc.yaml

It's a proposal, When we build ol-cesium in a subfolder , It tries to apply the eslint config from the parent folder. 
Set the root porperty to true avoid this.

Set the eslint as the root config file

---

src/olcs/contrib/manager.js

Add an event when 3D is toggled to the Cesium Manager.
```js
cesiumManager.on('change', (event) => {
  console.log('3D active: ', event.target.is3dEnabled());
});
```
Also add a `LOAD` event when cesium has been loaded.

Add 3d toggle & load events in manager

---

src/olcs/contrib/manager.js

New method in manger to set up a 3d view without transition.
Parameters are
- lon
- lat
- elevation
- heading
- pitch

Add method to init 3d with a view without transition

---

examples/imageWMS.html
examples/imageWMS.js
src/olcs/core.js

Aims to support `ImageWMS` when it is possible. For that, an alternative `TileWMS` source is created from the `ImageWMS` one and is used to create the Cesium `ImageryLayer`.
Support is not possible when ImageWMS
- has no `url`
- use an `ImageLoadFunction`
No ref to original `ImageWMS` source seems to be need, as the event only watch for `TileWMS` state to be `'ready'`.

Add ImageWMS sync support

---

examples/customProj.html
examples/customProj.js
src/olcs/core.js
src/olcs/core/olimageryprovider.js
src/olcs/util.js

During raster sync, if the source of the layer has a different projection than the view, layer is ignored.
This PR aims to avoid this limitation. 
- If the source projection is different from the view but still supported by Cesium (`4326`, `3857`) then it is added.
- If it is a custom projection other than the 2 aboves, we check if the source can support Cesium projection via (`olcs.proj.4326` and `olcs.proj.3857` properties) and if yes we create a new source with supported projection to add it to Cesium.

Allow layers from different projection if supported by Cesium

---

src/olcs/core.js

Keep default behavior:
If no projection is defined in the layer via `layer.getSource().getProjection()` or `layer.getSource().get('olcs.projection')`, then use map projection for the layer (that should support it because it is the one used for openlayers).

Fix source projection retrieval for WMS

---

externs/olcsx.js
src/olcs/featureconverter.js
src/olcs/vectorsynchronizer.js

For the meantime, during feature removal, only geometry of type `ol.geom.Point` were removing their corresponding potential billboard (only one cause it's a point).
But ol-cesium also manage multipoint and multi style, for example a `LineString` with a style with a `geometryFunction` returning a `MultiPoint`. In those cases, billboards were not cleared.
So the pool of billboard for a feature is now an array, and the array is cleared whatever the type of the geometry when the feature is removed.

Properly clear billboards on feature remove

---

src/olcs/abstractsynchronizer.js

This solves one problem we encountered: when adding an image layer with a source which initialization is delayed, the layer is not displayed in Cesium (but it is in OpenLayers).

Retry to add updated layers after they failed once

---

CHANGES.md
Cesium.externs.js
examples/reprojection.html
examples/reprojection.js
src/olcs/core.js
src/olcs/core/olimageryprovider.js

Add client side raster reprojection support

---

CHANGES.md
examples/groundvectors.js
src/olcs/FeatureConverter.js

Taking the ideas of @ediebold used in #603, I added support for clamped  `ol.geom.Circle` outline geometries.

added circle outline GroundPolyline

---

src/olcs/SynchronizedOverlay.js

#609 broke synchronized overlays due to:
- a bad commit;
- the call to super that moved up (race condition).

Fix SynchronizedOverlay with ES6 classes

---

examples/bing.html
examples/bing.js
src/olcs/RasterSynchronizer.js
src/olcs/core.js
src/olcs/core/OLImageryProvider.js

Some TileSources (TileUTFGrid, TileJSON and BingMaps, to date) define
their `setAttributions` function with a `frameState` argument,
provided by PluggableMap's POSTRENDER event in OpenLayers. With
ol-cesium, OLImageProvider calls `setAttributions` on instantiation,
without any arguments -- which, of course, results in an exception.
In this commit, we've implemented getTileCredits in order to
dynamically generate credits based on what's in the viewport.
An example using Bing (with the same credentials in OpenLayer's
repository) has been added to show the change in action.

Always rely on frameState to create attributions

---

package.json

Hello,
For any application using Webpack to build, we should point the `"module"` property (package.json) to the library source instead of its built version.
It also solves a problem that started to occur in ol-cesium 2.2: I got an error "_ol is not defined_" in the browser (I did not investigate further, but seems to be related to the "oldfashioned" library change from the 2.2 version).

Export module in package.json

---

src/olcs/FeatureConverter.js

Hi,
This fixes an issue when a feature style is customized through a StyleFunction.
The code:
```
style = featureStyleFunction.call(feature, resolution);
```
does not correctly execute because `call` function requires a context object passed as first argument.
The current context is not needed here, so we just need to call the function with the arguments, as it is done just after with `fallbackStyleFunction`
Thanks.

Fix custom vector styles

---

examples/fillstyle.html
examples/fillstyle.js
src/olcs/FeatureConverter.js
src/olcs/core.js

Hi,
When a surface style (`ol.style.Fill`) is defined as a CanvasPattern or CanvasGradient (as defined in the `ColorLike` type) in OpenLayers for a polygon, Cesium fails to display it.  
This change fixes this problem.

CanvasPattern and CanvasGradient as polygon surface style

---

CHANGES.md
examples/icon-position.html
examples/icon-position.js
src/olcs/FeatureConverter.js

Hello,
By default in ol-cesium, icons are positioned differently in 2D (default is the anchor in the center of the icon) and in 3D (icon is bottom-aligned).
This fixes this problem as it calculates Cesium Billboard pixel offset from OpenLayer anchor position.

Correctly map icon anchor from IconStyle to Billboard

---

src/olcs/SynchronizedOverlay.js

when cesium is configured with a terrain, the synchronized overlay with height 0 seems to be under the terrain, and changes the position depending on the viewpoint. 
This pull request fixes the problem and requests the height from the globe

calculate height for the SynchronizedOverlay using the globe.getHeight function

---

src/olcs/OverlaySynchronizer.js

Hi, 
during the ES6 Module updates this bug happend, but it only failed for overlays created before the synchronizer has been updated, so it didn't show in the overlay example.
This fixed the addOverlay function

fix overlaysynchronizer 

---

buildtools/webpack.prod.js
package.json

Hello,  
The build is failing if uglifyjs Webpack dependency is not installed.  
This change fixes the error when trying to build the library.

fix: update Webpack

---

CHANGES.md
src/olcs/OLCesium.js

Hello,  
I got an issue in my application when I tried to remove a draw interaction on the map while 3D mode was enabled.  
I can see that when switching to 3D, interactions are temporarily kept into a `pausedInteractions` list then re-applied when switching back to 2D.  
This change allows to update pausedInteractions array when interactions are added or removed from the map when 3D mode is enabled.

Synchronize interactions when in 3d mode

---

src/olcs/VectorSynchronizer.js

Ignore OL vectore tile layers during synchronization
since they are not supported currently and would cause
an error otherwise

Exclude vector tile layers from synchronization

---

src/olcs/FeatureConverter.js

In Cesium the offset of an entity is specified in pixels from it's center by
default. Openlayers uses the top left position as origin.
While the origin is already converted since #653, this does not consider any
scaling of the image that happens in Cesium at a later stage through the scale
parameter. With a scale < 1 this can result in images that are off by multiple
times their own size.
Multiplying the pixel offset with the scale of the image resolves the issue.
The icon-position example can be used to demonstrate this issue when a scale
parameter is added to the first icon.
```
diff --git a/examples/icon-position.js b/examples/icon-position.js
index 62fb17a..362e42b 100644
--- a/examples/icon-position.js
+++ b/examples/icon-position.js
@@ -28,6 +28,7 @@ icon1Feature.setStyle(new …
```

Fix conversion of icon anchor to pixelOffset

---

src/olcs/FeatureConverter.js

Wondering if there would be any interest in a way to provide more flexibility in generating billboards through ol-cesium. This is more of a jumping off point from a coding perspective. My goal was to be able to provide cesium specific options for the billboard generation.
A feature could now include the key `bbOptions` where you could provide members available to the [billboards](https://cesium.com/docs/cesiumjs-ref-doc/Billboard.html).
```javascript
feature.bbOptions = {
scaleByDistance: new Cesium.NearFarScalar(1.5e4, 1, 8.0e5, 0.0),
pixelOffsetScaleByDistance: new Cesium.NearFarScalar(1.5e4, 1, 8.0e5, 0)
}
```

Includes custom options from feature into billboard generation

---

src/olcs/core.js
src/olcs/core/OLImageryProvider.js

We are maintaining layers in our NgRx Store as part of the application state. Therefore we need to deep copy the layers including the projections when updating the state. Comparing projection objects therefore does not work in our case and we would be happy if the projection comparison could be switched to comparing them by their code.

Compare projections by code

---

src/olcs/OLCesium.ts

Correction for issues [#1065](https://github.com/openlayers/ol-cesium/issues/1065) and  [#981](https://github.com/openlayers/ol-cesium/issues/981)

Disables touch action on canvas to fix pinch zoom problem

---

examples/print.html
examples/print.js

Note that changing the "scale" changes the symbology. It would be interesting to find a @x2 version of OSM tiles and compare the quality.

Update the print example to generate bigger images

---

CHANGES.md
src/olcs/Camera.js

The old value produced visible discrepency between 2d and 3d on side-by-side examples.

Increase camera synchronization precision

---

src/olcs/SynchronizedOverlay.js

When I was looking at the source code, I found that the registration event in SynchronizedOverlay was duplicated, and I think it should be removable.

perf(overlay): delete duplicated code.

---

src/olcs/FeatureConverter.js

There is an OpenLayers vector layer `style` that has both `image` and `text` attributes, and the text cannot overlap with the image. So, it is necessary to set a one-way `offsetY` for the text. However, when synchronizing to OLCesium, the corresponding `Cesium.Label` instance was not offset. Therefore, I adjusted the relevant code for the offset attribute to support one-way offset for the text.

perf(text-offset): Unidirectional offset

---

.github/renovate.json

We should validate these manually.

Forbid renovate to automatically update minor ol and Cesium

---

examples/print.html
examples/print.js

We already have a scaling system. So the example was changed to use it.
Ideally we would use the https://cesium.com/learn/cesiumjs/ref-doc/CesiumWidget.html?classFilter=widge#resolutionScale property, see #1137.

Simplify scaling system example

---

src/olcs.ts

I want to pass a custom `createSynchronizers` function to the `OLCesium` constructor with the default `OverlaySynchronizer`, the default `VectorSynchronizer` and a custom `RasterSynchronizer`. I don't know why the `OverlaySynchronizer` isn't exported in the main file, if I import it from `olcs/src/olcs/OverlaySynchronizer`, there are typescript compilation errors, if I add the export to the `olcs.ts` file and import it from there, everything works just fine.

Add export for OverlaySynchronizer in olcs.ts

---

src/olcs/Camera.ts

When paning and zooming the 3d map, the pitch (tilt) and the heading of the camera were continuosly adapted by small steps in an unpredictable way. 
There is a guard flag in `Camera.updateView()` which causes the events from the ol map to be ignored, while the ol map is adjusted. Unfortunately the ol map events are generated asynchronously and the guard flag was already reset right at the end of `Camera.updateView()`. This was too early and so events would be handled which should have been ignored.

Account for asynchronous event generation in ol maps when synchronizing with the 2d map

---

src/olcs/AutoRenderLoop.ts
src/olcs/OLCesium.ts

This allows to only synchronize from 3d to 2d after the cesium camera stopped moving. This saves a lot of unnecessary overhead, if the 2d map is not visible anyways.
The default behavior is to synchronize continuously as before.

Optional synchronisation optimization 3d to 2d

---

CONTRIBUTING.md
examples/index.html
package.json

The examples were not working on dev environment after running `npm start` because there is a bug in parcel that is ignoring the distDir attribute in targets for `parcel serve`. I replaced with cli commands and added a `prestart` hook with the commands that were in `build-examples` to add parts that are not compiled by parcel (should we also investigate that?).
bug reports in parcel:
https://github.com/parcel-bundler/parcel/issues/8715
https://github.com/parcel-bundler/parcel/issues/8105
https://github.com/parcel-bundler/parcel/discussions/6778 
Also, should I just remove the targets object from the code?

fix: parcel serve target dist directory

---

src/olcs/OLCesium.ts

I can't see any reason why the `.js` is missing on these two imports (as far as I can see they are the only ones), and the fact they are missing is causing webpack to choke in a downstream project.

Fix missing .js extensions in imports

---

src/olcs.ts
src/olcs/OLCesium.ts

Downstream projects find it helpful to be able to reuse the type definition of the constructor options for the main OLCesium object.
I also corrected the type of the `sceneOptions` option: The `canvas` and `scene3DOnly` options are set internally and so should not be passed as part of the `sceneOptions`. Previously `canvas` strictly had to be passed as it is defined as a non-optional member of `SceneOptions`.

feature: Expose OLCesiumOptions
