build/jsdoc/api/conf.json
build/jsdoc/api/plugins/typedefs.js
externs/olcsx.js
src/ol3cesium.js

Reverts openlayers/ol3-cesium#147
The review comments where not addressed: no deprecation and path migration notice where added.
See https://github.com/openlayers/ol3-cesium/pull/147#issuecomment-69304024 for details.

Revert "Allow working with custom synchronizers"

---

CHANGES.md
build/jsdoc/api/conf.json
build/jsdoc/api/plugins/typedefs.js
externs/olcsx.js
src/ol3cesium.js

This is a revised version of #147 and replaces #150.
Thanks for any review.

Allow applications to use custom synchronizers

---

examples/dragbox.js
examples/epsg-4326.js
examples/exports.js
examples/main.js
examples/rastersync.js
examples/selection.js
examples/sidebyside.js
examples/synthvectors.js
examples/synthvectors_batch.js
examples/vectors.js

Use new single argument constructor in examples

---

Makefile

Will thus be automatically added to releases.
Closes #158.

Copy CHANGES.md to dist directory

---

build/build.js

Used the model of Openlayers3.

Add header to ol3cesium.js and ol3cesium-debug.js

---

Cesium.externs.js
Makefile
src/camera.js

Migrate to new stable versions of Ol3 and Cesium.

Use Ol 3.2 and Cesium 1.6

---

Cesium.externs.js
src/core.js

See AnalyticalGraphicsInc/cesium#2499.

Workaround minor regression in Cesium 1.6

---

Cesium.externs.js
src/camera.js

Use pitch and not removed apis

---

CHANGES.md

Preparation for the release 1.2.

Update CHANGES.md with release date

---

src/rastersynchronizer.js

Mark RasterSynchronizer @api

---

Cesium.externs.js
build/serve.js
src/camera.js
src/core.js

And also:
- change serving port from 3000 to 4000 to allow running both ol3 and ol3-cesium concurrently;
- add some documentation;
- add or update some Cesium externs.

Port to cesium 1.10 and minor improvements

---

Cesium.externs.js

Add drillpick, fix some return types and style.

Cesium externs

---

CHANGES.md
Cesium.externs.js
examples/rastersync.js
src/core/olimageryprovider.js

Require https://github.com/openlayers/ol3/pull/3759

Fix tilegrid issue

---

src/camera.js

Mark olcs.Camera#readFromView @api

---

src/core/olimageryprovider.js

Added optional function pickFeatures 

---

src/featureconverter.js

Allow other geometry types to be converted to billboards.

Relax geometry type of csAddBillboard

---

CHANGES.md

Release a new version depending on the latest August stable release of OpenLayers.
Then we will be able to merge PRs depending on OpenLayers master.

Prepare release 1.7

---

src/featureconverter.js

Allows to use different styles in 2D and 3D.
Depends on https://github.com/openlayers/ol3/pull/3977
Depends on https://github.com/openlayers/ol3/pull/3993

Trigger billboard image style loading

---

CHANGES.md
src/rastersynchronizer.js

This requires compiling with Closure.

Allows instanciating custom Cesium imageries

---

Makefile
build/generate-exports.js
build/ol3cesium.json
closure-util.json
package.json
src/featureconverter.js

Update compiler and library

---

src/abstractsynchronizer.js
src/core.js
src/core/olimageryprovider.js
src/dragbox.js
src/featureconverter.js
src/vectorsynchronizer.js

Use standard javascript instead.

Goog cleanup

---

README.md
examples/dragbox.js
examples/epsg-4326.js
examples/exports.js
examples/lazy.js
examples/main.js
examples/rastersync.js
examples/sidebyside.js
examples/synthvectors.js
examples/synthvectors_batch.js
examples/vectors.js

Update terrain provider url

---

examples/vectors.js
src/featureconverter.js

ol3-cesium failed to display a point feature which has only a text style, this PR fixes it.

Allow a point geometry to have only a text style

---

src/featureconverter.js

Verify the feature is still displayed on the map before creating the billboard.

Prevent adding removed feature

---

CHANGES.md
examples/rastersync.html
src/core.js
src/rastersynchronizer.js

Remove saturation, brightness and hue support which were removed in OL 3.

Port to OL 3.10.1 and Cesium 1.14

---

CHANGES.md
examples/vectors.html
src/autorenderloop.js
src/ol3cesium.js

Prepare release 1.9

---

examples/vectors.js
src/featureconverter.js
src/vectorsynchronizer.js

Synchronize features displayed using ol.layer.Image

---

Cesium.externs.js

Will only be available in th next cesium version.

Add Cesium.Fog in externs

---

examples/rastersync.html
examples/rastersync.js
examples/vectors.js

The Bing key was expired.
Add lighting effect.

Use OSM instead of Bing

---

CHANGES.md

Update CHANGES.md for release

---

CHANGES.md
Makefile
README.md
examples/epsg-4326.html
examples/exports.html
examples/inject_ol3_cesium.js
examples/kml.html
examples/lazy.html
examples/lazy.js
examples/main.html
examples/rastersync.html
examples/selection.html
examples/sidebyside.html
examples/synthvectors.html
examples/synthvectors_batch.html
examples/vectors.html

With this parameter, unminified source code is loaded instead of minified one. This is helpful for debugging.

Accept a mode=dev parameter in examples

---

Cesium.externs.js
Makefile
examples/inject_ol3_cesium.js
src/featureconverter.js

See https://github.com/AnalyticalGraphicsInc/cesium/issues/3656.

Use new geometryInstances property

---

src/featureconverter.js

Should fix https://github.com/openlayers/ol3-cesium/issues/329.

Fix test to createShadowVolume property

---

CHANGES.md
src/ol3cesium.js
src/olcs.js

See https://github.com/AnalyticalGraphicsInc/cesium/pull/3288 for details.
Demo: http://dev.camptocamp.com/files/gberaudo/olcs_dpi/examples/vectors.html

Honor devicePixelRatio (CSS4)

---

CHANGES.md

Update OpenLayers to version 3.15.1

---

src/camera.js
src/ol3cesium.js

This PR fixes a nasty bug and adds early checks.

Fix frustum aspect ratio and check earlier

---

build/build.js
package.json

See https://github.com/openlayers/ol3/pull/5151

Use fs-extra as fs and remove usage of graceful-fs

---

build/check-no-goog.sh
src/core.js

@oterral do you remember why that lines were needed?

Remove extra goog events

---

.npmignore
package.json

See https://www.npmjs.com/package/ol3-cesium.

Make sure dist is present in package published on npm

---

build/check-no-goog.sh
src/ol3cesium.js

closure-library code:
https://github.com/google/closure-library/blob/v20160822/closure/goog/dom/dom.js#L1252-L1262

Get rid of goog.dom.getNextElementSibling

---

Cesium.externs.js
src/featureconverter.js

Polygons with Holes didn't work correctly, this pullrequest fixes the problem.

fixed polygon holes

---

examples/main.html
examples/main.js
src/ol3cesium.js

This PR allow to specify a time for the Cesium rendering.
@gberaudo and @fredj review please ?

Use time from options

---

CHANGES.md
build/check-no-goog.sh
examples/rotate.html
examples/rotate.js
src/abstractsynchronizer.js
src/core.js
src/rastersynchronizer.js

Get ride of remaining closure library usage

---

examples/vectors.js
src/featureconverter.js

Use all the styles defined and display geometries coming from style

---

CHANGES.md
package.json

Closes: https://github.com/openlayers/ol-cesium/issues/465.

Port to Cesium 1.36

---

src/abstractsynchronizer.js
src/rastersynchronizer.js

RasterSynchonizer class added events that was never removed when the layer was removed.

Remove listeners created in raster synchronizer

---

src/featureconverter.js

Same as #484 but at an other place.

Manage null value of prims variable

---

CHANGES.md
src/olcs/featureconverter.js

See the ol.Feature "olcs.3d_geometry" property.

Allow dedicated 3D geometry for features

---

CHANGES.md
examples/lazy.html
package.json
src/olcs/contrib/manager.js
src/olcs/core.js

- add animation;
- rename to lowercase.

Enhance and rename toggle3d

---

Cesium.externs.js

And add missing entry for `Cesium.defaultValue` function

Remove duplicate entry en cesium externs

---

Cesium.externs.js

And normalize whitespaces in typedefs.

Fix url to API doc in Cesium.externs.js

---

CHANGES.md
Cesium.externs.js
package.json
src/olcs/contrib/manager.js
src/olcs/olcesium.js

More or less depends on https://github.com/AnalyticalGraphicsInc/cesium/pull/5993.

Small cosmetic changes

---

package/goog/asserts.js
package/package.json
package/readme.md

Provide and document ES6 version of goog

---

build/package.sh
package/package.json
src/olcs/abstractsynchronizer.js
src/olcs/core/olimageryprovider.js
src/olcs/olcesium.js
src/olcs/rastersynchronizer.js

Prepare for ol5

---

Cesium.externs.js

Add `Cesium3DTileset` and `Cesium3DTilesetOptions` externs.

Add Cesium3DTileset externs

---

CHANGES.md
Cesium.externs.js
package.json
src/olcs/autorenderloop.js
src/olcs/core/olimageryprovider.js
src/olcs/olcesium.js

Port to cesium 1.44 and rework autorenderloop

---

src/olcs/FeatureConverter.js

Allow empty text styles

---

package.json

Teach MS windows the meaning of env variables

---

CHANGES.md
examples/bing.html
examples/bing.js
src/olcs/OLCesium.js
src/olcs/RasterSynchronizer.js
src/olcs/core.js
src/olcs/core/OLImageryProvider.js

Replaces: #600.
There is also an issue in our Cesium version which will be fixed in camptocamp/cesium/pull/55.

Fix credits handling

---

CHANGES.md
Makefile
README.md
buildtools/webpack.examples.js
buildtools/webpack.library.js
examples/oldfashioned.html
src/index.library.js
src/olcs/Camera.js
src/olcs/contrib/Manager.js
src/olcs/math.js
webpack.config.js

Old fashioned example

---

CHANGES.md
examples/vectors.js
src/olcs/VectorSynchronizer.js

Fix missing source issue

---

src/olcs/FeatureConverter.js

Fix crash converting feature without style

---

src/olcs/core/OLImageryProvider.js

Correct a bug for non-standard tileGrid for WMTS layer.
Fixes :#741

Manage non-standard tileGrid WMTS

---

README.md

Change the way that the library is imported into Angular applications.

Update usage guidelines for Angular

---

.npmrc
package.json

Typedoc does not support newer typescript versions.
Closes: #962.

Fix typescript version

---

CONTRIBUTING.md
LICENSE

Same as OpenLayers: https://github.com/openlayers/openlayers/pull/7711

Stop requiring people to sign CLA

---

examples/icon-position.js
examples/rotate.js
examples/vectors.js
src/olcs/Camera.js
src/olcs/FeatureConverter.js
src/olcs/OLCesium.js
src/olcs/RasterSynchronizer.js
src/olcs/contrib/Manager.js
src/olcs/core.js
src/olcs/core/OLImageryProvider.js
src/olcs/util.js

Eblondel core util namedexports

---

src/olcs/AbstractSynchronizer.ts
src/olcs/Camera.js
src/olcs/OLCesium.ts
src/olcs/OverlaySynchronizer.js

Add destroy method to OLCesium

---

src/olcs/FeatureConverter.js

Fix options passing to Cesium.MaterialAppearance

---

src/olcs/OLCesium.ts

fix: cesium container is not initially hidden

---

src/olcs/OverlaySynchronizer.ts

fix: remove listeners if overlay is destroyed

---

CHANGES.md
package-lock.json
package.json
src/olcs/FeatureConverter.ts
src/olcs/core.ts

Also, remove useless buffer polyfill in dev mode.

Port to OpenLayers 9

---

.github/workflows/test.yml
CHANGES.md
package-lock.json
package.json
src/olcs/FeatureConverter.ts
src/olcs/dashPatternConversion.test.ts
tsconfig.json

Add support for dashed lines

---

CHANGES.md
src/olcs/Camera.ts

Fix wrong unlistener condition

---

CHANGES.md
PROPERTIES.md
examples/customProj.js
examples/vectors.js
package-lock.json
package.json
src/olcs/FeatureConverter.ts
src/olcs/core.ts
src/olcs/core/OLImageryProvider.ts
src/olcs/util.ts

Convert all image WMS load functions
